module3
AlexandraRyzvanovich/webpack-app pull request #1
Opened 2021-08-29 23:18 UTC by AlexandraRyzvanovich

2021-08-31 16:41 UTC, sushchenja requested changes

2021-08-31 16:41 UTC, sushchenja commented on src/Index.js
> +ReactDOM.render(<Header />, document.getElementById("header"));
use one entry point

2021-08-31 16:41 UTC, sushchenja commented on src/components/app.js
> +      <Fragment>
unnecessary fragment

2021-08-31 16:41 UTC, sushchenja commented on src/components/movieSorter.js
> +      </Fragment>
unnecessary fragment. to render the line pls use a pseudo element

2021-08-31 16:41 UTC, sushchenja commented on src/components/movieSorter.js
> +  getAllMovies() {
what is the purpose of this method

2021-08-31 16:41 UTC, sushchenja commented on src/components/movieList.js
> +    list: PropTypes.any,
don't use any

2021-08-31 16:41 UTC, sushchenja commented on src/components/movieList.js
> +          {this.propTypes?.list?.size || this.getDefaultList().size} MOVIES
you can't use propTypes like this

2021-08-31 16:41 UTC, sushchenja commented on src/components/movieList.js
> +  getDefaultList() {
let's try to implement a container component which will provide all necessary data. and leave this component as presentational

2021-08-31 16:41 UTC, sushchenja commented on src/components/movieList.js
> +        ;
semicolon

2021-08-31 16:41 UTC, sushchenja commented on src/service/movieService.js
> +        <Movie
service should provide only pure data

2021-08-31 16:41 UTC, sushchenja commented on src/service/movieService.js
> +import React from "react";
there is no place for react and component imports

2021-08-31 16:41 UTC, sushchenja commented on src/components/movieList.js
> +          {this.propTypes?.list?.items || this.getDefaultList().items}
get data from service, pass it to the view component and render it there

2021-09-20 20:02 UTC, sushchenja requested changes

2021-09-20 20:02 UTC, sushchenja commented on src/components/movieComponent.js
> +      isDeleteOpened: !showDelete,
you can use functional setState

2021-09-23 21:27 UTC, AlexandraRyzvanovich commented on src/components/addPopup.js
>  import "./../styles/header.scss";
fixed

2021-09-23 21:27 UTC, AlexandraRyzvanovich commented on src/styles/movie.scss
> +// .dropdown-content {
fixed

2021-09-23 21:27 UTC, AlexandraRyzvanovich commented on src/components/movieAppContainer.js
> +    let isDefaultHeaderOpened = this.state.isDefaultHeaderOpened;
fixed

2021-09-23 21:27 UTC, AlexandraRyzvanovich commented on src/components/movieAppContainer.js
> +    return (
fixed

2021-09-23 21:28 UTC, AlexandraRyzvanovich commented on src/components/movieAppContainer.js
> +          isOpened={this.state.isOpened}
fixed

2021-09-23 21:28 UTC, AlexandraRyzvanovich commented on src/components/movieListComponent.js
> +    <Fragment>
fixed

2021-09-23 21:28 UTC, AlexandraRyzvanovich commented on src/components/movieListComponent.js
> +          key={index + ""}
fixed

2021-09-23 21:28 UTC, AlexandraRyzvanovich commented on src/components/movieListComponent.js
> +  const movies = useCallback(callback, deps);
fixed

2021-09-23 21:28 UTC, AlexandraRyzvanovich commented on src/components/movieInfoHeader.js
> +    let movie = MovieService.getFullMovieInfo(props.id);
fixed

2021-09-23 21:29 UTC, AlexandraRyzvanovich commented on src/components/movieComponent.js
> +      isDeleteOpened: !showDelete,
fixed

2021-09-23 21:29 UTC, merged

2021-10-01 09:44 UTC, sushchenja commented on src/components/editPopup.js
> +  };
all this line could be changed to custom hook: const movie = useMovie(1)